name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  00
  #ENV ASPNETCORE_URLS=http://%2A:5000/
  ENTRYPOINT ["/app/Leonardo.Web"]
  guillaume chervet — Aujourd’hui à 13:43
  docker run -p 8080:8080  --rm fibo
  guillaume chervet — Aujourd’hui à 14:34
publish_docker:
  needs: [tags, build_docker]
  runs-on: ubuntu-latest
  steps:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.100-preview.7.23376.3
    - run: dotnet test /p:CollectCoverage=true /p:CoverletOutputFormat=opencover /p:CoverletOutput=./coverage/opencover.xml
    - run: dotnet publish ./src/Leonardo.Web/Leonardo.Web.csproj --self-contained true --output ./win-x64/fibonacci -c Release -r win-x64 /p:PublishSingleFile=true /p:PublishTrimmed=true /p:PublishReadyToRun=true
    - name: Upload WebApp1 Build Artifact
      uses: actions/upload-artifact@v2
      with:
        name: Publish win-x64 Fibonacci
        path: ./win-x64/fibonacci
